[package]
name = "pem"
version = "0.2.0"
authors = ["Jonathan Creekmore <jonathan@thecreekmores.org>"]
repository = "https://github.com/jcreekmore/pem-rs.git"
homepage = "https://github.com/jcreekmore/pem-rs.git"
license = "MIT"
readme = "README.md"
documentation = "http://jcreekmore.github.io/pem-rs/"
description = "Parse and encode PEM-encoded data."

[dependencies]
rustc-serialize = "0.3"
regex = "0.1"
