[package]
authors = ["Jonathan Creekmore <jonathan@thecreekmores.org>"]
description = "Parse and encode PEM-encoded data."
documentation = "http://jcreekmore.github.io/pem-rs/"
homepage = "https://github.com/jcreekmore/pem-rs.git"
license = "MIT"
name = "pem"
readme = "README.md"
repository = "https://github.com/jcreekmore/pem-rs.git"
version = "0.3.0"

[dependencies]
error-chain = "0.10.0"
lazy_static = "0.2.6"
regex = "0.2"
rustc-serialize = "0.3"
