[package]
authors = ["Jonathan Creekmore <jonathan@thecreekmores.org>"]
description = "Parse and encode PEM-encoded data."
documentation = "https://docs.rs/pem/"
homepage = "https://github.com/jcreekmore/pem-rs.git"
license = "MIT"
name = "pem"
readme = "README.md"
repository = "https://github.com/jcreekmore/pem-rs.git"
version = "0.5.1-pre"
categories = [ "cryptography" ]

[dependencies]
base64 = "0.9.0"
error-chain = "0.11.0"
lazy_static = "1.0"
regex = "0.2"

[badges]
travis-ci = { repository = "jcreekmore/pem-rs" }
